import os


os.system('pip install requests')
os.system('pip install colored')
os.system('pip install pystyle')
os.system('pip install datetime')
os.system('pip install keyboard')
os.system('pip install tkinter')
os.system('pip install tls_client')
os.system('pip install threading')
os.system('pip install easygui')
os.system('pip install colorama')
os.system('pip install pynput')
os.system('pip install websocket')
os.system('pip install fake_useragent')
os.system('pip install httpx')
os.system('pip install emoji')
os.system('pip install bs4')
os.system('pip install discum==1.1.0')
os.system('pip install discord')